### ISSUE TITLE
[Bug] Discover scrolling of Toonily and Manhwa18 causes crash

### ISSUE THREAD

**Issue by HellDuke-Astaroth** [Paperback-iOS/h-extensions#6]
When scrolling through that discover tabs for both of the mention tabs, the app would crash 100% of the time.

**Comment by ConradWeiser** [comment]
This is reported for __both__ sources? I'll take a look and see what's going on. I knew that I was having this issue on Toonily months ago, although it was patched and tested to be fine again. I wonder if another little quirk came up. 

I'll be in touch!

**Comment by ConradWeiser** [comment]
I've ran an audit on what Toonily is returning for the `getHomeSection` method, and it turns out that all of the data is formed properly, there is no nulls, and all of the image URLs are resolvable. 

All of the return objects are surrounded in their proper wrapper methods.

Something interesting, is that if both Toonily and nHentai is loaded, if you scroll on the discover page for nHentai's section, the app also crashes.

But as soon as Toonily is removed, you may scroll through nHentai's section fine without any problems. By itself, Manhwa18 is completely safe, but with Toonily added, Manhwa18 also starts to crash in the way that's described.

The only outlier in any data I saw being returned was addressed in ac035195027166fa2e964e8867f7092f19d509d6 where the rating values for manga were being set to NaN due to a parse failure. But even after that patch, the issue still has not been resolved. 

The source logs are not yielding any helpful data back. I may have to release a temporary debug version of the source which dumps more data to the log.

**Comment by ConradWeiser** [comment]
Seems to be fixed
